name: build

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout bgutil-ytdlp-pot-provider
        uses: actions/checkout@v4
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: server/
          file: server/Dockerfile
          push: false
          tags: brainicism/bgutil-ytdlp-pot-provider:ci
