name: Create release
on: 
  workflow_dispatch:

jobs:
  release:
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: "3.8"

    - name: Install Hatch
      run: pipx install hatch

    - name: Set variables
      id: set_variables
      shell:  bash
      run: |
        tag=$(git for-each-ref refs/tags --sort=-taggerdate --format='%(refname:strip=2)' --count=1)
        cd plugin/
        version=v$(hatch project metadata | jq -r .version)
        cd ..
        # if [ -z "${tag}" ]; then
        #   git tag ${version}
        #   tag=${version}
        # fi
        cd plugin/
        echo "::group::Variables"
        cat << EOF | tee -a "$GITHUB_OUTPUT"
        tag=${tag}
        version=${version}
        EOF
        echo "::endgroup::"
    - name: Bundle and create release
      env:
        GH_TOKEN: ${{ github.token }}
        tag: ${{ steps.set_variables.outputs.tag }}
        version: ${{ steps.set_variables.outputs.version }}
      if: |
        env.tag != env.version
      run: |
        cd plugin/
        project_name="$(hatch project metadata | jq -r .name)"
        sources="$(\
          hatch run default:pip list --verbose --format json \
          | jq -r '.[] | select(.editable_project_location == null) | "\(.name);\(.location)"' \
        )"
        echo "::group::Dependencies"
        printf '%s\n' "${sources}"
        echo "::endgroup::"
        mkdir bundle/
        cp -r yt_dlp_plugins bundle/
        while IFS=';' read -r name path; do
          if [[ ! "${name}" =~ ^(pip|setuptools|wheel|yt-dlp)$ ]]; then
            package_name="$(tr '[:upper:]' '[:lower:]' <<<"${name}" | sed 's/-/_/g')"
            cp -r "${path}/${package_name}" bundle/
          fi
        done <<<"${sources}"
        cd bundle/
        find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
        zip -9 --recurse-paths "${project_name}" *
        gh release create "${version}" --latest \
          --title "${project_name} ${version}" \
          "${project_name}.zip"
  release_pypi:
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build hatchling

    - name: Build
      run: |
        cp README.md plugin/
        cd plugin/
        rm -rf dist/**
        printf '%s\n\n' \
          "Official repository: <${{ github.server_url }}/${{ github.repository }}>" > ./README.md.new
        cat ./README.md >> ./README.md.new && mv -f ./README.md.new ./README.md
        python -m build --no-isolation .

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        packages-dir: plugin/dist
  release_docker:
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: env|sort  # debugging

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: server/
        file: server/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
