name: Run tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TEST_ARGS: >-
    -vF --color always
    --extractor-args "youtube:player-client=web,web_music,mweb;pot_trace=true;fetch_pot=always"
    --ignore-no-formats-error

jobs:
  lint-format:
    name: Lint and format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff and autopep8
        run: pip install ruff autopep8
      - name: Python lint check (Ruff)
        run: ruff check --output-format=github -v plugin/
      - name: Python lint check (autopep8)
        if: always()
        run: autopep8 --diff plugin/
      - name: Install server dependencies
        if: always()
        run: cd server && npm ci
      - name: Server lint check (ESlint)
        if: always()
        run: cd server && npx eslint --max-warnings=0 src/
      - name: Server format check (Prettier)
        if: always()
        run: cd server && npx prettier --check 'src/**/*.{js,ts}'

  node-script-method:
    name: Test plugin (node script method)
    uses: ./.github/workflows/ci-method.yml
    with:
      runtime: 'node'
      method: 'script'

  node-server-method:
    name: Test plugin (node server method)
    uses: ./.github/workflows/ci-method.yml
    with:
      runtime: 'node'
      method: 'server'

  deno-script-method:
    name: Test plugin (deno script method)
    uses: ./.github/workflows/ci-method.yml
    with:
      runtime: 'deno'
      method: 'script'

  deno-server-method:
    name: Test plugin (deno server method)
    uses: ./.github/workflows/ci-method.yml
    with:
      runtime: 'deno'
      method: 'server'
